### PR TITLE
Data channel: Add Close and OnClose

### LINKED ISSUE #329: nil pointer in WriteDataChannel
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x42a9b7e]

goroutine 12 [running]:
github.com/pions/datachannel.(*DataChannel).WriteDataChannel(0x0, 0xc0001d9490, 0x4, 0x8, 0x400bf01, 0x432cec0, 0xc00027c200, 0xc0000427b0)
        /Users/max/go/pkg/mod/github.com/pions/datachannel@v1.0.0/datachannel.go:205 +0x4e
github.com/pions/webrtc.(*RTCDataChannel).Send(0xc0000cc580, 0x43d3340, 0xc00027c200, 0xc00027c200, 0x4)
        /Users/max/go/pkg/mod/github.com/pions/webrtc@v1.2.1-0.20181228023033-acc342fa5887/rtcdatachannel.go:229 +0x93
main.(*Demo).startConn.func4(0xc0000cc580)
        /Users/max/projects/asciirtc/main.go:93 +0xec
created by main.(*Demo).startConn
        /Users/max/projects/asciirtc/main.go:91 +0x3dd
```

Reproduction scenario: Send on an RTCDataChannel before it is opened.
TODO: Check the spec for the right way to handle this and implement it.

### PR DESCRIPTION
**Pull request by backkem**
Relates to #180 
Resolves #329

TODO:
- [x] Update dependencies once pions/datachannel#5 lands.
- [x] CI all the things!
- [x] Update dependencies once pions/sctp#10 lands.

### CODE REVIEW

File: rtcdatachannel.go [hunk 1]
```diff
@@ -256,12 +289,23 @@ func (d *RTCDataChannel) handleOpen(dc *datachannel.DataChannel) {
 }
 
 func (d *RTCDataChannel) readLoop() {
+	const dataChannelBufferSize = 16384 // Lowest common denominator among browsers
```
Comment (Sean-Der) [inline rtcdatachannel.go]: mind moving that to the top of the file?
