### PR TITLE
[WIP] Fix race in DataChannel.open()

### LINKED ISSUE #505: Race in DataChannel.open()
In my app, I am seeing a race condition at the following line:
https://github.com/pions/webrtc/blob/90b85e8c7a5bf92405d2a07fde0069bcfd3ab526/datachannel.go#L189
```go
	dc, err := datachannel.Dial(d.sctpTransport.association, *d.ID, cfg)
	if err != nil {
		d.mu.RUnlock()
		return err
	}

	d.ReadyState = DataChannelStateOpen // <------------ race
	d.mu.RUnlock()

	d.handleOpen(dc)
	return nil
}
```
I believe, we need to use write lock instead of read lock here.

### PR DESCRIPTION
**Pull request by enobufs**
Now it uses write lock in this PR.
No regression in unit tests, race detection nor golangci-lint in my local run.

I noticed the was a race (reported as #509), not caused by this modification.

Resolves #505

### CODE REVIEW

File: datachannel.go [hunk 1]
```diff
@@ -182,12 +182,12 @@ func (d *DataChannel) open(sctpTransport *SCTPTransport) error {
 
 	dc, err := datachannel.Dial(d.sctpTransport.association, *d.ID, cfg)
 	if err != nil {
-		d.mu.RUnlock()
+		d.mu.Unlock()
 		return err
 	}
 
 	d.ReadyState = DataChannelStateOpen
```
Comment (Sean-Der) [inline datachannel.go]: Can you make this so we just take the writelock for setting `d.ReadyState` I just don't want to be wasteful having a write lock for the whole function. If this is a bad idea please push back!

```
d.mu.RUnlock()
d.mu.Lock()
d.ReadyState = DataChannelStateOpen
d.mu.Unlock()
```

Comment (enobufs) [reply datachannel.go]: I think, it wouldn't give us much because:
1. This method would virtually 100% succeed in production use (bug-free).
1. Sticking with only one kind of lock is relatively less error-prone.
1. DataChannel.open() won't be called that often anyway (I wouldn't worry)

Comment (Sean-Der) [reply datachannel.go]: A agree with all that, I was overthinking it. More complicated code for no real gain :)
