### PR TITLE
Stop Create(Offer/Answer) from setting localDesc

### LINKED ISSUE #309: CreateOffer and CreateAnswer shouldn't call setLocalDescription
Currently these two methods incorrectly call `setLocalDescription` causing us to deviate from the spec.

This is going to cause user breakage, and we will have to figure out a way a nice way to notify users.

### PR DESCRIPTION
**Pull request by Sean-Der**
This deviates from the WebRTC spec, so we need to fix it. This is a
massively breaking change, so we need to figure out the best way to help
users with this.

I also renamed our RTCPeerConnection constructor. The hope is that
people will refer to the examples/backlog and see what changed.

Resolves #309

-----

I added all the devs as a heads up, if you think there is a better way we can handle this I am all ears!

### CODE REVIEW

File: examples/data-channels-close/main.go [hunk 1]
```diff
@@ -90,10 +90,13 @@ func main() {
 	err = peerConnection.SetRemoteDescription(offer)
 	util.Check(err)
 
-	// Sets the LocalDescription, and starts our UDP listeners
+	// Create answer
 	answer, err := peerConnection.CreateAnswer(nil)
 	util.Check(err)
 
+	// Sets the LocalDescription, and starts our UDP listeners
+	util.Check(peerConnection.SetLocalDescription(answer))
```
Comment (backkem) [inline examples/data-channels-close/main.go]: Maybe put the Check on a new line? It just shows off the API a tiny bit better, I feel?

Sidenote: I've seen util.Check() (and other parts of util) leak into peoples projects. We should think about ways to avoid that.

File: examples/data-channels-create/main.go [hunk 2]
```diff
@@ -65,6 +65,9 @@ func main() {
 	offer, err := peerConnection.CreateOffer(nil)
 	util.Check(err)
 
+	// Sets the LocalDescription, and starts our UDP listeners
+	util.Check(peerConnection.SetLocalDescription(offer))
```
Comment (backkem) [inline examples/data-channels-create/main.go]: new line?

File: examples/data-channels-detach-create/main.go [hunk 3]
```diff
@@ -62,6 +62,9 @@ func main() {
 	offer, err := peerConnection.CreateOffer(nil)
 	util.Check(err)
 
+	// Sets the LocalDescription, and starts our UDP listeners
+	util.Check(peerConnection.SetLocalDescription(offer))
```
Comment (backkem) [inline examples/data-channels-detach-create/main.go]: new line?

File: examples/data-channels-detach/main.go [hunk 4]
```diff
@@ -67,10 +67,13 @@ func main() {
 	err = peerConnection.SetRemoteDescription(offer)
 	util.Check(err)
 
-	// Sets the LocalDescription, and starts our UDP listeners
+	// Create answer
 	answer, err := peerConnection.CreateAnswer(nil)
 	util.Check(err)
 
+	// Sets the LocalDescription, and starts our UDP listeners
+	util.Check(peerConnection.SetLocalDescription(answer))
```
Comment (backkem) [inline examples/data-channels-detach/main.go]: new line?

File: examples/data-channels/main.go [hunk 5]
```diff
@@ -70,10 +70,13 @@ func main() {
 	err = peerConnection.SetRemoteDescription(offer)
 	util.Check(err)
 
-	// Sets the LocalDescription, and starts our UDP listeners
+	// Create an answer
 	answer, err := peerConnection.CreateAnswer(nil)
 	util.Check(err)
 
+	// Sets the LocalDescription, and starts our UDP listeners
+	util.Check(peerConnection.SetLocalDescription(answer))
```
Comment (backkem) [inline examples/data-channels/main.go]: new line?

File: examples/gstreamer-receive/main.go [hunk 6]
```diff
@@ -70,10 +70,13 @@ func main() {
 	err = peerConnection.SetRemoteDescription(offer)
 	util.Check(err)
 
-	// Sets the LocalDescription, and starts our UDP listeners
+	// Create an answer
 	answer, err := peerConnection.CreateAnswer(nil)
 	util.Check(err)
 
+	// Sets the LocalDescription, and starts our UDP listeners
+	util.Check(peerConnection.SetLocalDescription(answer))
```
Comment (backkem) [inline examples/gstreamer-receive/main.go]: new line?

File: examples/gstreamer-send-offer/main.go [hunk 7]
```diff
@@ -51,6 +51,9 @@ func main() {
 	offer, err := peerConnection.CreateOffer(nil)
 	util.Check(err)
 
+	// Sets the LocalDescription, and starts our UDP listeners
+	util.Check(peerConnection.SetLocalDescription(offer))
```
Comment (backkem) [inline examples/gstreamer-send-offer/main.go]: new line?

File: examples/gstreamer-send/main.go [hunk 8]
```diff
@@ -60,10 +60,13 @@ func main() {
 	err = peerConnection.SetRemoteDescription(offer)
 	util.Check(err)
 
-	// Sets the LocalDescription, and starts our UDP listeners
+	// Create an answer
 	answer, err := peerConnection.CreateAnswer(nil)
 	util.Check(err)
 
+	// Sets the LocalDescription, and starts our UDP listeners
+	util.Check(peerConnection.SetLocalDescription(answer))
```
Comment (backkem) [inline examples/gstreamer-send/main.go]: new line?

File: examples/janus-gateway/streaming/main.go [hunk 9]
```diff
@@ -107,6 +107,8 @@ func main() {
 		answer, err := peerConnection.CreateAnswer(nil)
 		util.Check(err)
 
+		util.Check(peerConnection.SetLocalDescription(answer))
```
Comment (backkem) [inline examples/janus-gateway/streaming/main.go]: new line?

File: examples/janus-gateway/video-room/main.go [hunk 10]
```diff
@@ -71,6 +71,8 @@ func main() {
 	offer, err := peerConnection.CreateOffer(nil)
 	util.Check(err)
 
+	util.Check(peerConnection.SetLocalDescription(offer))
```
Comment (backkem) [inline examples/janus-gateway/video-room/main.go]: new line?

File: examples/pion-to-pion/answer/main.go [hunk 11]
```diff
@@ -77,10 +77,13 @@ func main() {
 	err = peerConnection.SetRemoteDescription(offer)
 	util.Check(err)
 
-	// Sets the LocalDescription, and starts our UDP listeners
+	// Create answer
 	answer, err := peerConnection.CreateAnswer(nil)
 	util.Check(err)
 
+	// Sets the LocalDescription, and starts our UDP listeners
+	util.Check(peerConnection.SetLocalDescription(answer))
```
Comment (backkem) [inline examples/pion-to-pion/answer/main.go]: new line?

File: examples/pion-to-pion/offer/main.go [hunk 12]
```diff
@@ -72,6 +72,9 @@ func main() {
 	offer, err := peerConnection.CreateOffer(nil)
 	util.Check(err)
 
+	// Sets the LocalDescription, and starts our UDP listeners
+	util.Check(peerConnection.SetLocalDescription(offer))
```
Comment (backkem) [inline examples/pion-to-pion/offer/main.go]: new line?

File: examples/save-to-disk/main.go [hunk 13]
```diff
@@ -73,10 +73,13 @@ func main() {
 	err = peerConnection.SetRemoteDescription(offer)
 	util.Check(err)
 
-	// Sets the LocalDescription, and starts our UDP listeners
+	// Create answer
 	answer, err := peerConnection.CreateAnswer(nil)
 	util.Check(err)
 
+	// Sets the LocalDescription, and starts our UDP listeners
+	util.Check(peerConnection.SetLocalDescription(answer))
```
Comment (backkem) [inline examples/save-to-disk/main.go]: new line?

File: examples/sfu/main.go [hunk 14]
```diff
@@ -111,10 +111,13 @@ func main() {
 	// Set the remote SessionDescription
 	util.Check(peerConnection.SetRemoteDescription(offer))
 
-	// Sets the LocalDescription, and starts our UDP listeners
+	// Create answer
 	answer, err := peerConnection.CreateAnswer(nil)
 	util.Check(err)
 
+	// Sets the LocalDescription, and starts our UDP listeners
+	util.Check(peerConnection.SetLocalDescription(answer))
```
Comment (backkem) [inline examples/sfu/main.go]: new line?

File: examples/sfu/main.go [hunk 15]
```diff
@@ -146,10 +149,13 @@ func main() {
 		err = peerConnection.SetRemoteDescription(recvOnlyOffer)
 		util.Check(err)
 
-		// Sets the LocalDescription, and starts our UDP listeners
+		// Create answer
 		answer, err := peerConnection.CreateAnswer(nil)
 		util.Check(err)
 
+		// Sets the LocalDescription, and starts our UDP listeners
+		util.Check(peerConnection.SetLocalDescription(answer))
```
Comment (backkem) [inline examples/sfu/main.go]: new line?

**Comment by backkem** [comment]
Btw, projects using modules will have to change their import path to `github.com/pions/webrtc/v2` anyway if we release as v2.0.0.

File: examples/data-channels-close/main.go (hunk 1 above)
Comment (mjmac) [reply examples/data-channels-close/main.go]: It would be a little silly, but maybe move util under examples/internal/util? Just to make it a bit more explicit... Maybe also drop a README.md/and or code comments to the effect that nothing in that package is intended to be public API and could break at any moment.

File: api.go [hunk 16]
```diff
@@ -89,8 +89,8 @@ func RegisterDefaultCodecs() {
 
 // PeerConnection API
 
-// New using the default API.
+// NewRTCPeerConnection using the default API.
 // See API.NewRTCPeerConnection for details.
-func New(configuration RTCConfiguration) (*RTCPeerConnection, error) {
+func NewRTCPeerConnection(configuration RTCConfiguration) (*RTCPeerConnection, error) {
```
Comment (mjmac) [inline api.go]: 👍

File: examples/data-channels-close/main.go (hunk 1 above)
Comment (maxhawkins) [reply examples/data-channels-close/main.go]: Or maybe remove util all together? I think it's an anti-pattern.

https://dave.cheney.net/2019/01/08/avoid-package-names-like-base-util-or-common

Comment (Sean-Der) [reply examples/data-channels-close/main.go]: 👍 to moving the util stuff under an `internal` (and just not allowing people to use it as a library)

I see a lot of people using and it was never really intended, we eventually will break it also.
